name: Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 20
      uses: actions/setup-node@v3
      with:
        node-version: 20.x
        cache: 'npm'
    - name: Install Dependencies
      run: npm install
    - name: Fix audit
      run: npm audit fix
    - name: Run Integration Tests
      run: npm run test:unit
    - name: Display SoftUni Username
      run: echo "gabcho333"
